Support vpn over udp

diff --git a/bin/nvpn b/bin/nvpn
--- a/bin/nvpn
+++ b/bin/nvpn
@@ -7,14 +7,20 @@
 ## https://developer-old.gnome.org/NetworkManager/stable/settings-vpn.html
 
 NVPN_ENDPOINT="https://nordvpn.com/wp-admin/admin-ajax.php?action=servers_recommendations"
-TYPE="tcp"
+
+type="${1:-tcp}"
+case $type in
+	tcp|udp );;
+	*		) echo "invalid type: ${type}" && exit 1;;
+esac
 
 host="$(curl GET "${NVPN_ENDPOINT}" 2> /dev/null | jq -r '.[0].hostname')"
-name="${host}.${TYPE}"
-file="/etc/openvpn/ovpn_${TYPE}/${name}.ovpn"
+name="${host}.${type}"
 
 con_import(){
-	file="$1"
+	type=$1
+	name=$2
+	file="/etc/openvpn/ovpn_${type}/${name}.ovpn"
 	nmcli con import --temporary type openvpn file "${file}"
 }
 
@@ -37,7 +43,7 @@ con_start(){
 
 if ! nmcli --fields name connection show | grep "${name}"
 then
-	con_import "${file}" \
+	con_import "${type}" "${name}" \
 	&& con_modify "${name}" "vpn.persistent" 				 "yes" \
 	&& con_modify "${name}" "connection.autoconnect-retries" "0" \
 	&& con_modify "${name}" "+vpn.data" 					 "username=${NVPN_USER}"
